# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56e34bf122f6d5c0436f8dfadc3f83f57954206a5d859ac1584c0e142d96d59862f54be83deb3b9a72cbff5f440430308b53ec1b00f20f91a4b9cb79d4c3c14

test:
  secret_key_base: 20bd828ff76ebe12c06d0e7c82be68a65b3d606a89d221efed36983f288af6d1d278e21261b33e1c0e968c9ef6c2b8748807fa927d4c6611146709ea6598f4c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
